<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Outatime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Strings.json" LogicalName="Outatime.Strings.json" />
    <InternalsVisibleTo Include="Outatime.Tests" />
  </ItemGroup>
</Project>
